### ISSUE TITLE
KeyError: ('problem_setup', 'task')

### ISSUE THREAD

**Issue by dirknbr** [romanpogodin/kernel-ci-testing#1]
I get this config error when I try to run toy_data_experiment.py 

```
python3 toy_data_experiment.py 

Traceback (most recent call last):
  File "/home/.../python/kernel_ci/kernel-ci-testing-main/toy_data_experiment.py", line 222, in <module>
    make_config()
  File "/home/.../python/kernel_ci/kernel-ci-testing-main/toy_data_experiment.py", line 216, in make_config
    config.validate(mode='stderr')
  File "/home/../.local/lib/python3.11/site-packages/fastargs/config.py", line 213, in validate
    got = self.content[path]
          ~~~~~~~~~~~~^^^^^^
KeyError: ('problem_setup', 'task')
``

**Comment by dirknbr** [comment]
fixed now by running

```
python3 toy_data_experiment.py --problem_setup.task get_xzy_randn
```
